import { theme } from '../theme';

export const styles = {
  container: { backgroundColor: theme.colors.background, padding: '40px 20px', display: 'flex', justifyContent: 'center', alignItems: 'center', fontFamily: 'system-ui, sans-serif', paddingBottom: theme.spacing.bottomNavPadding },
  tarjeta: { width: '100%', maxWidth: '700px', backgroundColor: '#141416', borderRadius: '24px', border: '1px solid rgba(255,255,255,0.05)', overflow: 'hidden', boxShadow: '0 20px 40px rgba(0,0,0,0.5)', position: 'relative' },
  bannerPortada: { width: '100%', height: '160px', backgroundColor: '#1F1F23', position: 'relative', overflow: 'hidden', cursor: 'pointer' },
  imagenPortadaImg: { width: '100%', height: '100%', objectFit: 'cover' },
  bannerVacio: { width: '100%', height: '100%', background: 'linear-gradient(135deg, #1f1f23 0%, #2c2c35 100%)' },
  portadaOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.4)', color: '#FFF', fontSize: '12px', fontWeight: '700', display: 'flex', alignItems: 'center', justifyContent: 'center', opacity: 0, transition: 'opacity 0.2s', ':hover': { opacity: 1 } },
  badgePuntos: { position: 'absolute', top: '20px', right: '20px', backgroundColor: 'rgba(57, 255, 20, 0.15)', border: '1px solid #39FF14', padding: '6px 14px', borderRadius: '30px', display: 'flex', flexDirection: 'column', alignItems: 'center', boxShadow: '0 4px 12px rgba(57, 255, 20, 0.2)', zIndex: 3 },
  puntosNumero: { color: theme.colors.primary, fontSize: '16px', fontWeight: '800', lineHeight: '1' },
  puntosLabel: { color: '#FFF', fontSize: '9px', fontWeight: '700', marginTop: '2px', letterSpacing: '0.5px' },
  avatarSeccion: { display: 'flex', justifyContent: 'center', marginTop: '-60px', marginBottom: '15px', position: 'relative', zIndex: '2' },
  avatarContenedor: { width: '120px', height: '120px', borderRadius: '50%', backgroundColor: '#1C1C1E', border: '4px solid #141416', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', position: 'relative', overflow: 'hidden', boxShadow: '0 8px 24px rgba(0,0,0,0.4)' },
  avatarLetra: { fontSize: '40px', color: '#8E8E93', fontWeight: '700' },
  imagenImagen: { width: '100%', height: '100%', objectFit: 'cover' },
  avatarOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: 'rgba(18, 18, 20, 0.8)', color: '#fff', fontSize: '10px', fontWeight: '700', textAlign: 'center', padding: '6px 0', borderTop: '1px solid rgba(255,255,255,0.1)' },
  titulo: { color: '#FFF', fontSize: '24px', fontWeight: '800', textAlign: 'center', margin: '10px 0 25px 0', letterSpacing: '-0.5px' },
  gridForm: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '20px', padding: '0 30px' },
  grupo: { display: 'flex', flexDirection: 'column', gap: '8px' },
  grupoCompleto: { display: 'flex', flexDirection: 'column', gap: '8px', padding: '20px 30px' },
  label: { color: '#A0A0A5', fontSize: '13px', fontWeight: '600', letterSpacing: '0.3px' },
  input: { backgroundColor: '#1A1A1E', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '12px', padding: '14px', color: '#FFF', fontSize: '14px', outline: 'none', transition: 'border-color 0.2s' },
  inputDisabled: { opacity: 0.5, cursor: 'not-allowed', backgroundColor: '#121214' },
  select: { backgroundColor: '#1A1A1E', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '12px', padding: '14px', color: '#FFF', fontSize: '14px', outline: 'none', cursor: 'pointer' },
  optgroup: { backgroundColor: '#141416', color: theme.colors.primary, fontWeight: '700' },
  textarea: { backgroundColor: '#1A1A1E', border: '1px solid rgba(255,255,255,0.08)', borderRadius: '12px', padding: '14px', color: '#FFF', fontSize: '14px', outline: 'none', minHeight: '90px', resize: 'vertical', fontFamily: 'inherit' },
  contenedorBotones: { padding: '20px 30px 40px 30px', display: 'flex', flexDirection: 'column', gap: '12px' },
  botonGuardar: { backgroundColor: theme.colors.primary, color: '#000', border: 'none', padding: '16px', borderRadius: '14px', fontSize: '15px', fontWeight: '700', cursor: 'pointer', boxShadow: '0 4px 15px rgba(57, 255, 20, 0.3)', transition: 'transform 0.2s' },
  botonLogout: { backgroundColor: 'transparent', color: '#FF453A', border: '1px solid rgba(255, 69, 58, 0.2)', padding: '14px', borderRadius: '14px', fontSize: '14px', fontWeight: '600', cursor: 'pointer' },
  error: { margin: '0 30px 20px 30px', padding: '12px', backgroundColor: 'rgba(255,69,58,0.1)', border: '1px solid #FF453A', color: '#FF453A', borderRadius: '10px', fontSize: '13px', textAlign: 'center' },
  exito: { margin: '0 30px 20px 30px', padding: '12px', backgroundColor: 'rgba(57,255,20,0.1)', border: '1px solid #39FF14', color: theme.colors.primary, borderRadius: '10px', fontSize: '13px', textAlign: 'center' }
}
