import { theme } from '../theme';

const surface = 'rgba(22, 22, 24, 0.7)';
const surfaceSolid = '#161618';
const borderSubtle = 'rgba(255, 255, 255, 0.05)';
const borderDefault = 'rgba(255, 255, 255, 0.08)';
const textSecondary = '#8E8E93';

export const styles = {
  screenContainer: {
    paddingBottom: theme.spacing.bottomNavPadding,
    backgroundColor: 'transparent',
    width: '100%',
    boxSizing: 'border-box',
    color: theme.colors.text,
  },
  headerHero: {
    position: 'relative',
    height: '240px',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
  },
  headerOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(to bottom, rgba(10,10,11,0.35) 0%, rgba(10,10,11,0.88) 65%, rgba(10,10,11,1) 100%)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  topBar: { display: 'flex', alignItems: 'center', padding: '16px 20px', gap: '12px' },
  backButton: {
    background: 'rgba(255,255,255,0.05)',
    border: `1px solid ${borderDefault}`,
    cursor: 'pointer',
    padding: '8px',
    display: 'flex',
    borderRadius: '12px',
    outline: 'none',
  },
  logoContainer: { display: 'flex', alignItems: 'center', gap: '8px' },
  logoIcon: { width: '22px', height: '22px', borderRadius: '4px' },
  logoText: { color: theme.colors.text, fontWeight: '800', fontSize: '13px', letterSpacing: '1px' },
  heroTitles: { padding: '0 20px', display: 'flex', flexDirection: 'column' },
  etiquetaTorneo: {
    color: theme.colors.primary,
    fontSize: '11px',
    fontWeight: '700',
    letterSpacing: '1.5px',
    marginBottom: '4px',
  },
  tituloTorneo: {
    color: theme.colors.text,
    fontSize: '26px',
    fontWeight: '900',
    margin: 0,
    textTransform: 'uppercase',
    letterSpacing: '-0.5px',
  },
  tabsMenu: { display: 'flex', padding: '0 20px', borderBottom: `1px solid ${borderDefault}` },
  tabItem: {
    flex: 1,
    background: 'transparent',
    border: 'none',
    borderBottom: '3px solid transparent',
    color: textSecondary,
    padding: '14px 0',
    fontSize: '12px',
    fontWeight: '700',
    cursor: 'pointer',
    letterSpacing: '0.5px',
    transition: 'all 0.2s',
    outline: 'none',
  },
  tabItemActivo: { color: theme.colors.primary, borderBottom: `3px solid ${theme.colors.primary}` },
  mainContent: { padding: '24px 20px 0' },

  infoGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: '12px',
    marginBottom: '8px',
  },
  infoCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    padding: '16px',
    borderRadius: '16px',
    backgroundColor: surface,
    border: `1px solid ${borderSubtle}`,
    boxShadow: '0 8px 32px rgba(0,0,0,0.24)',
    backdropFilter: 'blur(20px)',
    minHeight: '118px',
  },
  infoIconWrap: {
    width: '32px',
    height: '32px',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(57, 255, 20, 0.08)',
    border: '1px solid rgba(57, 255, 20, 0.15)',
  },
  infoIcon: { fontSize: '20px' },
  infoLabel: {
    fontSize: '11px',
    color: textSecondary,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  infoValue: { fontSize: '15px', color: theme.colors.text, fontWeight: '700', lineHeight: '1.3' },

  sectionHeaderRow: { marginTop: '8px' },
  sectionTitle: {
    margin: 0,
    fontSize: '18px',
    fontWeight: '800',
    color: theme.colors.text,
    letterSpacing: '0.08em',
  },
  categoryList: { display: 'flex', flexDirection: 'column', gap: '12px' },
  categoryCard: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    backgroundColor: surface,
    border: `1px solid ${borderSubtle}`,
    borderRadius: '16px',
    padding: '14px 16px',
    cursor: 'pointer',
    boxShadow: '0 8px 32px rgba(0,0,0,0.24)',
    backdropFilter: 'blur(20px)',
    outline: 'none',
    color: theme.colors.text,
  },
  categoryLeft: { display: 'flex', alignItems: 'center', gap: '12px', flex: 1 },
  categoryIcon: { fontSize: '18px' },
  categoryTextWrap: { display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: '2px' },
  categoryTitle: { fontSize: '16px', fontWeight: '800', color: theme.colors.text },
  categoryMeta: { fontSize: '11px', color: textSecondary },
  categoryAction: { display: 'flex', alignItems: 'center', gap: '8px', color: theme.colors.primary },
  categoryActionText: { fontSize: '11px', fontWeight: '800', letterSpacing: '0.12em' },
  categoryActionArrow: { fontSize: '20px', lineHeight: 1 },

  detailPanel: { display: 'flex', flexDirection: 'column', gap: '16px' },
  categoryHeaderRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '10px' },
  categoryTitleBlock: { flex: 1 },
  categoryHeading: { margin: 0, fontSize: '28px', fontWeight: '800', color: theme.colors.text },
  statusBadge: {
    padding: '6px 10px',
    borderRadius: '999px',
    backgroundColor: 'rgba(57, 255, 20, 0.12)',
    color: theme.colors.primary,
    border: '1px solid rgba(57, 255, 20, 0.35)',
    fontSize: '10px',
    fontWeight: '800',
    letterSpacing: '0.08em',
  },

  searchWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '0 12px',
    height: '46px',
    borderRadius: '14px',
    border: `1px solid ${borderDefault}`,
    backgroundColor: surfaceSolid,
  },
  searchIcon: { fontSize: '18px', color: textSecondary },
  searchInput: {
    flex: 1,
    border: 'none',
    background: 'transparent',
    outline: 'none',
    color: theme.colors.text,
    fontSize: '14px',
  },

  subTabsRow: { display: 'flex', gap: '8px', borderBottom: `1px solid ${borderDefault}` },
  subTabButton: {
    flex: 1,
    background: 'transparent',
    border: 'none',
    padding: '12px 6px',
    cursor: 'pointer',
    color: textSecondary,
    fontWeight: '700',
    fontSize: '13px',
    borderBottom: '2px solid transparent',
    outline: 'none',
  },
  subTabButtonActive: {
    color: theme.colors.text,
    borderBottom: `2px solid ${theme.colors.primary}`,
  },

  chipRow: { display: 'flex', gap: '8px', overflowX: 'auto', paddingBottom: '6px' },
  chip: {
    flexShrink: 0,
    borderRadius: '999px',
    backgroundColor: 'rgba(255,255,255,0.05)',
    border: `1px solid ${borderDefault}`,
    padding: '8px 12px',
    fontSize: '12px',
    fontWeight: '700',
    color: textSecondary,
    cursor: 'pointer',
    outline: 'none',
  },
  chipActive: {
    backgroundColor: 'rgba(57, 255, 20, 0.15)',
    borderColor: theme.colors.primary,
    color: theme.colors.primary,
  },

  matchList: { display: 'flex', flexDirection: 'column', gap: '12px' },
  matchCardDetail: {
    display: 'flex',
    backgroundColor: surface,
    borderRadius: '16px',
    border: `1px solid ${borderSubtle}`,
    overflow: 'hidden',
    boxShadow: '0 8px 32px rgba(0,0,0,0.24)',
    backdropFilter: 'blur(20px)',
  },
  timeColumnDetail: {
    width: '76px',
    backgroundColor: 'rgba(57, 255, 20, 0.06)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRight: `1px solid ${borderSubtle}`,
  },
  timeDetail: { fontSize: '16px', fontWeight: '800', color: theme.colors.primary },
  matchContent: { flex: 1, padding: '12px 14px', display: 'flex', flexDirection: 'column', gap: '10px' },
  badgeRowDetail: { display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
  stateBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '4px 8px',
    borderRadius: '999px',
    backgroundColor: 'rgba(57, 255, 20, 0.1)',
    color: theme.colors.primary,
    fontSize: '9px',
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    border: '1px solid rgba(57, 255, 20, 0.2)',
  },
  teamsRow: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '12px' },
  teamGroup: { display: 'flex', alignItems: 'center', gap: '8px', flex: 1 },
  teamLabel: { fontSize: '10px', color: textSecondary, fontWeight: '700' },
  teamName: { fontSize: '13px', fontWeight: '700', color: theme.colors.text },
  scoreGroup: { display: 'flex', alignItems: 'center', gap: '4px', minWidth: '48px', justifyContent: 'center' },
  scoreValue: { fontSize: '15px', fontWeight: '800', color: theme.colors.text },
  scoreSeparator: { fontSize: '12px', color: textSecondary },
  scorePlaceholder: { fontSize: '15px', color: textSecondary },
  matchFooter: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    paddingTop: '8px',
    borderTop: `1px solid ${borderSubtle}`,
  },
  locationIcon: { fontSize: '12px' },
  locationTextDetail: { fontSize: '11px', color: textSecondary },

  zonesList: { display: 'flex', flexDirection: 'column', gap: '12px' },
  zoneCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    backgroundColor: surface,
    borderRadius: '16px',
    border: `1px solid ${borderSubtle}`,
    padding: '16px',
    boxShadow: '0 8px 32px rgba(0,0,0,0.24)',
    backdropFilter: 'blur(20px)',
  },
  zoneHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
  zoneTitle: { fontSize: '16px', fontWeight: '800', color: theme.colors.text },
  positionsTable: { borderRadius: '12px', overflow: 'hidden', border: `1px solid ${borderDefault}` },
  positionsHeader: {
    display: 'grid',
    gridTemplateColumns: '1fr auto',
    padding: '10px 12px',
    backgroundColor: surfaceSolid,
    fontSize: '10px',
    fontWeight: '800',
    color: textSecondary,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  tableLabel: { textAlign: 'left' },
  tableLabelRight: { textAlign: 'right' },
  positionRow: {
    display: 'grid',
    gridTemplateColumns: '1fr auto',
    alignItems: 'center',
    padding: '10px 12px',
    borderTop: `1px solid ${borderSubtle}`,
    backgroundColor: 'rgba(10, 10, 11, 0.5)',
  },
  parejaName: { fontSize: '13px', color: theme.colors.text, fontWeight: '700' },
  puntosValue: { fontSize: '13px', color: theme.colors.primary, fontWeight: '800', textAlign: 'right' },
  zoneMatchesList: { display: 'flex', flexDirection: 'column', gap: '8px' },
  zoneMatchItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    padding: '10px 12px',
    borderRadius: '10px',
    backgroundColor: 'rgba(10, 10, 11, 0.5)',
    border: `1px solid ${borderSubtle}`,
  },
  locationPin: { fontSize: '12px' },
  zoneMatchTextWrap: { display: 'flex', flexDirection: 'column', flex: 1 },
  zoneMatchTeams: { fontSize: '12px', fontWeight: '700', color: theme.colors.text },
  zoneMatchMeta: { fontSize: '10px', color: textSecondary },
  zoneResult: { fontSize: '12px', fontWeight: '800', color: theme.colors.primary },

  bracketWrap: { overflow: 'auto', paddingBottom: '8px' },
  bracketBoard: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(150px, 1fr))',
    gap: '16px',
    minWidth: '420px',
    alignItems: 'stretch',
  },
  bracketNode: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    backgroundColor: surface,
    borderRadius: '12px',
    border: `1px solid ${borderSubtle}`,
    padding: '12px',
    boxShadow: '0 8px 32px rgba(0,0,0,0.24)',
    position: 'relative',
  },
  nodeMeta: { fontSize: '10px', color: textSecondary, fontWeight: '700' },
  nodeState: {
    fontSize: '9px',
    color: theme.colors.primary,
    fontWeight: '800',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
  nodeTeam: { fontSize: '12px', color: theme.colors.text, fontWeight: '700' },

  centerContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '50vh',
    flexDirection: 'column',
  },
  spinner: {
    width: '32px',
    height: '32px',
    border: '3px solid rgba(57, 255, 20, 0.1)',
    borderTopColor: theme.colors.primary,
    borderRadius: '50%',
    animation: 'spin 1s linear infinite',
  },
  alerta: {
    padding: '20px',
    backgroundColor: surface,
    borderRadius: '16px',
    border: `1px solid ${borderDefault}`,
    textAlign: 'center',
  },
  btnVolver: {
    marginTop: '12px',
    padding: '8px 16px',
    backgroundColor: 'rgba(255,255,255,0.05)',
    color: theme.colors.text,
    border: `1px solid ${borderDefault}`,
    borderRadius: '8px',
    cursor: 'pointer',
    outline: 'none',
  },

  actionFooter: {
    padding: '24px 20px 0',
    marginTop: '8px',
  },
  btnInscribirse: {
    width: '100%',
    height: '54px',
    backgroundColor: theme.colors.primary,
    border: 'none',
    borderRadius: '16px',
    color: theme.colors.background,
    fontSize: '15px',
    fontWeight: '800',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 24px',
    boxShadow: '0 8px 20px rgba(57, 255, 20, 0.25)',
    transition: 'transform 0.2s ease',
    outline: 'none',
  },
  precioBadge: {
    backgroundColor: 'rgba(10, 10, 11, 0.25)',
    padding: '6px 12px',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: '900',
    color: theme.colors.background,
  },
  badgeCerrado: {
    width: '100%',
    height: '50px',
    backgroundColor: surface,
    border: `1px solid ${borderDefault}`,
    borderRadius: '16px',
    color: textSecondary,
    fontSize: '13px',
    fontWeight: '600',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeInscripto: {
    width: '100%',
    minHeight: '50px',
    backgroundColor: 'rgba(57, 255, 20, 0.08)',
    border: '1px solid rgba(57, 255, 20, 0.35)',
    borderRadius: '16px',
    color: theme.colors.primary,
    fontSize: '13px',
    fontWeight: '700',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },

  };