import { theme } from '../theme';

export const styles = {
  screenContainer: {
    paddingBottom: theme.spacing.bottomNavPadding,
    backgroundColor: 'transparent',
    width: '100%',
    boxSizing: 'border-box',
    color: theme.colors.text,
    position: 'relative'
  },
  headerHero: {
    position: 'relative',
    height: '240px',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
  },
  headerOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    background: 'linear-gradient(to bottom, rgba(10, 10, 11, 0.5) 0%, rgba(10, 10, 11, 1) 100%)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  topBar: { display: 'flex', alignItems: 'center', padding: '16px 20px', gap: '12px' },
  backButton: {
    background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)', 
    cursor: 'pointer', padding: '8px', display: 'flex', borderRadius: '12px', outline: 'none'
  },
  logoContainer: { display: 'flex', alignItems: 'center', gap: '8px' },
  logoIcon: { width: '22px', height: '22px', borderRadius: '4px' }, 
  logoText: { color: '#FFF', fontWeight: '800', fontSize: '13px', letterSpacing: '1px' },
  heroTitles: { padding: '0 20px', display: 'flex', flexDirection: 'column' },
  etiquetaTorneo: { color: theme.colors.primary, fontSize: '11px', fontWeight: '700', letterSpacing: '1.5px', marginBottom: '4px' },
  tituloTorneo: { color: theme.colors.text, fontSize: '26px', fontWeight: '900', margin: 0, textTransform: 'uppercase', letterSpacing: '-0.5px' },
  tabsMenu: { display: 'flex', padding: '0 20px', borderBottom: '1px solid rgba(255,255,255,0.05)' },
  tabItem: {
    flex: 1, background: 'transparent', border: 'none', borderBottom: '3px solid transparent',
    color: '#8E8E93', padding: '14px 0', fontSize: '12px', fontWeight: '700', cursor: 'pointer',
    letterSpacing: '0.5px', transition: 'all 0.2s'
  },
  tabItemActivo: { color: theme.colors.primary, borderBottom: '3px solid #39FF14' },
  mainContent: { padding: '24px 20px 160px 20px' }, // Ampliado ligeramente para evitar solapamientos con botones fijos
  tabSection: { display: 'flex', flexDirection: 'column' },
  dateSelectorRow: { display: 'flex', gap: '10px', overflowX: 'auto', paddingBottom: '14px' },
  datePill: {
    border: '1px solid rgba(255,255,255,0.08)', borderRadius: '16px', padding: '10px 16px',
    backgroundColor: 'rgba(22, 22, 24, 0.6)', display: 'flex', flexDirection: 'column', alignItems: 'center',
    minWidth: '75px', cursor: 'pointer', transition: 'all 0.2s'
  },
  datePillActivo: { borderColor: theme.colors.primary, backgroundColor: 'rgba(57, 255, 20, 0.05)' },
  datePillDia: { fontSize: '11px', fontWeight: '600', color: '#8E8E93' },
  datePillNum: { fontSize: '13px', fontWeight: '700', color: '#FFF', marginTop: '2px' },
  textNeon: { color: theme.colors.primary },
  dateSubtitleRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', margin: '14px 0' },
  dateSubtitleText: { fontSize: '14px', fontWeight: '700', color: '#FFF' },
  matchesCount: { fontSize: '12px', color: '#8E8E93', fontWeight: '500' },
  matchesList: { display: 'flex', flexDirection: 'column', gap: '14px' },
  matchCard: {
    display: 'flex', backgroundColor: 'rgba(22, 22, 24, 0.7)', backdropFilter: 'blur(10px)',
    borderRadius: '20px', border: '1px solid rgba(255,255,255,0.04)', overflow: 'hidden'
  },
  timeColumn: {
    display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center',
    padding: '16px', minWidth: '65px', backgroundColor: 'rgba(255,255,255,0.02)', borderRight: '1px solid rgba(255,255,255,0.04)'
  },
  timeText: { fontSize: '18px', fontWeight: '800', color: theme.colors.primary },
  dayText: { fontSize: '11px', fontWeight: '600', color: '#8E8E93', marginTop: '2px' },
  detailsColumn: { padding: '16px', flex: 1, display: 'flex', flexDirection: 'column', gap: '10px' },
  badgesRow: { display: 'flex', alignItems: 'center', gap: '6px', flexWrap: 'wrap' },
  badgeEstado: (estado) => ({
    backgroundColor: estado === 'finalizado' ? 'rgba(255,255,255,0.05)' : 'rgba(0,122,255,0.1)',
    color: estado === 'finalizado' ? '#8E8E93' : '#007AFF',
    padding: '4px 8px', borderRadius: '6px', fontSize: '9px', fontWeight: '800', display: 'inline-block'
  }),
  badgeCategoria: { backgroundColor: 'rgba(255,255,255,0.06)', color: '#FFF', padding: '4px 8px', borderRadius: '6px', fontSize: '9px', fontWeight: '700' },
  badgeZona: { backgroundColor: 'rgba(57, 255, 20, 0.1)', color: theme.colors.primary, padding: '4px 8px', borderRadius: '6px', fontSize: '9px', fontWeight: '700' },
  playersBlock: { display: 'flex', flexDirection: 'column', gap: '4px', margin: '4px 0' },
  playerLine: { fontSize: '13px', fontWeight: '600', color: '#FFF' },
  vsText: { fontSize: '10px', fontWeight: '800', color: '#8E8E93', paddingLeft: '14px' },
  resultadoRow: { display: 'flex', gap: '6px', fontSize: '12px', backgroundColor: 'rgba(255,255,255,0.03)', padding: '6px 10px', borderRadius: '8px' },
  resultadoLabel: { color: '#8E8E93', fontWeight: '600' },
  resultadoValue: { color: theme.colors.primary, fontWeight: '700' },
  locationRow: { display: 'flex', alignItems: 'center', gap: '6px', borderTop: '1px solid rgba(255,255,255,0.04)', paddingTop: '8px' },
  locationText: { fontSize: '11px', color: '#8E8E93', fontWeight: '500' },
  galeriaHeader: { marginBottom: '16px' },
  galeriaFiltros: { display: 'flex', gap: '8px' },
  galeriaPill: { padding: '8px 16px', borderRadius: '14px', border: '1px solid rgba(255,255,255,0.08)', backgroundColor: 'transparent', fontSize: '13px', fontWeight: '600', color: '#8E8E93', cursor: 'pointer', outline: 'none' },
  galeriaPillActivo: { backgroundColor: 'rgba(57, 255, 20, 0.1)', borderColor: theme.colors.primary, color: theme.colors.primary },
  uploadSection: { display: 'flex', flexDirection: 'column', gap: '12px', marginBottom: '18px', padding: '18px', borderRadius: '20px', backgroundColor: 'rgba(255,255,255,0.03)', border: '1px solid rgba(57,255,20,0.12)' },
  uploadControls: { display: 'flex', flexDirection: 'column', gap: '10px' },
  btnFilePicker: { display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: '8px', padding: '12px 16px', backgroundColor: 'rgba(10, 10, 11, 0.95)', border: '1px solid rgba(57,255,20,0.4)', borderRadius: '16px', color: theme.colors.text, fontWeight: '700', cursor: 'pointer', outline: 'none', width: '100%', transition: 'all 0.2s' },
  uploadInput: { position: 'absolute', width: '1px', height: '1px', padding: 0, margin: '-1px', overflow: 'hidden', clip: 'rect(0,0,0,0)', border: 0 },
  fileName: { color: '#8E8E93', fontSize: '13px', lineHeight: '1.4', minHeight: '20px', wordBreak: 'break-word' },
  btnSubirImagen: {
    width: '100%',
    height: '50px',
    backgroundColor: theme.colors.primary,
    border: 'none',
    borderRadius: '16px',
    color: theme.colors.background,
    fontSize: '14px',
    fontWeight: '800',
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0 20px',
    boxShadow: '0 8px 20px rgba(57, 255, 20, 0.25)',
    transition: 'opacity 0.2s ease',
    outline: 'none'
  },
  galeriaGrid: { display: 'flex', flexDirection: 'column', gap: '16px' },
  imageCard: { width: '100%', height: '200px', borderRadius: '20px', overflow: 'hidden', border: '1px solid rgba(255,255,255,0.05)' },
  img: { width: '100%', height: '100%', objectFit: 'cover' },
  zonaCard: { backgroundColor: 'rgba(22, 22, 24, 0.75)', borderRadius: '20px', border: '1px solid rgba(255,255,255,0.06)', padding: '18px', display: 'flex', flexDirection: 'column', gap: '16px' },
  zonaHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '12px', flexWrap: 'wrap' },
  zonaNombre: { fontSize: '16px', fontWeight: '800', color: theme.colors.text },
  zonaCategoria: { fontSize: '12px', color: '#8E8E93', textTransform: 'uppercase', letterSpacing: '0.8px', marginTop: '4px' },
  zonaMeta: { display: 'flex', gap: '12px', alignItems: 'center', flexWrap: 'wrap' },
  zonaMetaText: { fontSize: '12px', color: '#8E8E93' },
  zonaPartidosList: { display: 'flex', flexDirection: 'column', gap: '12px' },
  matchCardNested: { display: 'flex', flexDirection: 'column', gap: '10px', backgroundColor: 'rgba(255,255,255,0.03)', borderRadius: '16px', padding: '14px', border: '1px solid rgba(255,255,255,0.04)' },
  parejasList: { display: 'flex', flexDirection: 'column', gap: '10px' },
  parejaItem: { padding: '12px 14px', backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: '14px', display: 'flex', justifyContent: 'space-between', gap: '10px', fontSize: '13px', color: '#fff' },
  noDataText: { fontSize: '13px', color: '#8E8E93', textAlign: 'center' },
  centerContainer: { display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '50vh', flexDirection: 'column' },
  spinner: { width: '32px', height: '32px', border: '3px solid rgba(57, 255, 20, 0.1)', borderTopColor: theme.colors.primary, borderRadius: '50%' },
  alerta: { padding: '20px', backgroundColor: 'rgba(255, 77, 77, 0.05)', borderRadius: '16px', border: '1px solid rgba(255, 77, 77, 0.2)', textAlign: 'center' },
  btnVolver: { marginTop: '12px', padding: '8px 16px', backgroundColor: 'rgba(255,255,255,0.05)', color: '#FFF', border: '1px solid rgba(255,255,255,0.1)', borderRadius: '8px', cursor: 'pointer', outline: 'none' },
  noMatches: { textAlign: 'center', padding: '40px 20px', color: '#8E8E93', fontSize: '13px' },

  // 🔥 ESTILOS CONTAINER FIJO INFERIOR
  fixedActionContainer: {
    position: 'fixed',
    bottom: '96px', // Altura recomendada para no superponerse con un BottomNavigation estándar
    left: '50%',
    transform: 'translateX(-50%)',
    width: '100%',
    maxWidth: '460px',
    padding: '0 20px',
    boxSizing: 'border-box',
    zIndex: 999
  },
  btnInscribirse: {
    width: '100%',
    height: '54px',
    backgroundColor: theme.colors.primary,
    border: 'none',
    borderRadius: '18px',
    color: theme.colors.background,
    fontSize: '15px',
    fontWeight: '800',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 24px',
    boxShadow: '0 8px 24px rgba(57, 255, 20, 0.3)',
    transition: 'transform 0.2s ease',
    outline: 'none'
  },
  precioBadge: {
    backgroundColor: 'rgba(10, 10, 11, 0.12)',
    padding: '6px 12px',
    borderRadius: '10px',
    fontSize: '14px',
    fontWeight: '900'
  },
  badgeCerrado: {
    width: '100%',
    height: '50px',
    backgroundColor: 'rgba(22, 22, 24, 0.8)',
    backdropFilter: 'blur(10px)',
    border: '1px solid rgba(255,255,255,0.05)',
    borderRadius: '18px',
    color: '#8E8E93',
    fontSize: '13px',
    fontWeight: '600',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center'
  },
  badgeInscripto: {
    width: '100%',
    minHeight: '50px',
    backgroundColor: 'rgba(57, 255, 20, 0.12)',
    border: '1px solid rgba(57, 255, 20, 0.25)',
    borderRadius: '18px',
    color: theme.colors.primary,
    fontSize: '13px',
    fontWeight: '700',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center'
  }
}
